.nr PS 10p
.nr VS 12p
.nr PSINCR 6p
.nr GROWPS 2
.nr HM 0.5i
.nr FM 0.5i
.nr PO 0.5i
.nr LL 7i
.fam T
.ss 12 0

.defcolor linecolor rgb 0.6f 0.6f 0.6f
.defcolor headingcolor rgb 0.5f 0.5f 0.5f

.de heading
.   nf
.   ps 14p
.   B "\\$1"
\h'0n'\v'-1.2n'\
\m[headingcolor]\
\l'\\n(.lu\(ul'\
\m[default]
.   ps 10
.   sp -.2
.   fi
..
.DS C
.ps 18
.B "Tanmoy Sarkar"
.ps 10
seniorsarkar.de@gmail.com
.DE
.TS
tab(;) nospaces;
l rx .
Kampa Lake Road
Vill.- Nagdaha
P.O.- Kampa
Dist.- North 24 Parganas
West Bengal, India;T{
.I "+91-7982143662"
T}
PIN- 743193;T{
.I "https://github.com/elvenkingfeanor"
T}
.TE
.heading "Summary of Qualifications"
.LP
Analytical and detail-oriented professional with 6 years of biological sciences research background.
.TS
tab(;) nospaces;
rW12|lx.
\m[default]Core Skills\m[linecolor];T{
\(bu 
.B "Stem cell culture protocols"
Well versed in primary stem cell culture including tissue isolation, enrichment, cryopreservation, cell separation and FACS, characterization, quantitation, and lysis.
.br
\(bu
.B "Molecular biological procedures"
Well acquainted with 2D-PAGE, ELISA, MALDI-TOF, Western blotting, gene cloning and plasmid pBR322 vector engineering, electroporation, bacterial cell culture, qRT-PCR, RT-PCR, primer designing, restriction mapping, epigenetic profiling.
.br
\(bu
.B "Medical physiology practices"
Familiar with biochemical, hematological, histological and microbial studies including experimental physiological studies, slide preparation and staining, and microscopy.
.br
\(bu
.B "Bioinformatics strategies"
Informed on BLAST, FASTA3, ClustalW
.br
\(bu
.B "Biostatistical techniques"
Knowledgeable with t-tests, Mann-Whitney tests, Chi-square tests, ANOVA analyses.
.sp .5
T}
\m[default]Communications Skills\m[linecolor];T{
Excellent verbal and written communications, and proposal drafting talents. Easily instill trust and confidence in colleagues.
.sp .5
T}
\m[default]Technical skills\m[linecolor];T{
\(bu
.B "Biological Instrumentation softwares"
BD FACScalibur, Roche LightCycler 480, Biorad Image Lab, Nanodrop 1000
.br
\(bu
.B "Image creation and quantitation softwares"
ImageJ, Inkscape, GIMP, imagemagick
.br
\(bu
.B "Document editing and management softwares"
nvim, groff \**, LaTeX, markdown, git, diff, patch, xargs, echo, cat, cut, paste, tr, grep, find, awk, sed, fzf, tree, regex
.br
\(bu
.B "Statistical and graph plotting softwares"
R, gnuplot, ttyplot
.br
\(bu
.B "Sysadmin and other softwares"
bash, systemd, grub, fdisk, top, dd, mkfs, time, ssh, kill, ping, df, du, lsblk, curl, wget, cron, mount, mtp, adb, chmod, chgrp
.sp .5
T}
\m[default]Key Strengths\m[linecolor];T{
Finely-tuned analytical skills with a dedication to expanding subject knowledge and workplace competencies through continuing training. Unparalleled multitasking and time management skills.
.sp .5
T}
.TE
\m[default]
.FS
This document was prepared in nvim text editor using groff typesetting language.
.FE
.heading "Professional Experience"
.TS
tab(;) nospaces;
rW10|lx.
\m[default]2014 - 2019\m[linecolor];T{
.B "CSIR-Institute for Genomics & Integrative Biology"
\(en New Delhi
.br
.I "Research Fellow"
.br
Meticulously worked under the supervision of Dr. Sagarika Biswas to accomplish:
.br
\(bu
setup viable cell culture laboratory and standardized stem cell culture protocols
.br
\(bu
performed RNA and protein studies on patient samples
.br
\(bu
carried out animal handling and dissection in accordance with ethical committee procedures
.br
\(bu
additionally, arranged seminars, guided trainees, collected samples, and other laboratory related subsidiary works
.br
\(en thesis titled
.I "Cytokine-mediated modulation of stem cell behaviour in rheumatoid arthritis".
.sp .5
T}
\m[default]2011 - 2012\m[linecolor];T{
.B "DBT-Centre for DNA Fingerprinting & Diagnostics"
\(en Hyderabad
.br
.I "Research Fellow"
.br
Worked under the guidance of Dr. Subhadeep Chatterjee to achieve:
.br
\(bu
restriction enzyme-based plasmid modifications towards bacterial genetic engineering
.br
\(en thesis titled
.I "Probing plant-microbe interactions in Xanthomonas quorum sensing".
.sp .5
T}
.TE
\m[default]
.heading "Educational Qualifications"
.TS
tab(;) nospaces;
rW10|lx.
\m[default]2016\m[linecolor];T{
.B "Senior Research Fellow"
\(en University Grants Commission
.br
.I "CSIR-Institute of Genomics & Integrative Biology, New Delhi"
.sp .5
T}
\m[default]2014\m[linecolor];T{
.B "Junior Research Fellow"
\(en University Grants Commission
.br
.I "CSIR-Institute of Genomics & Integrative Biology, New Delhi"
.sp .5
T}
\m[default]2011\m[linecolor];T{
.B "Junior Research Fellow"
\(en Council for Scientific & Industrial Research
.br
.I "DBT-Centre for DNA Fingerprinting & Diagnostics, Hyderabad"
.sp .5
T}
\m[default]2011\m[linecolor];T{
.B "Master of Science"
\(en Utkal University, Bhubaneswar
.br
.I "PG Department of Biotechnology, Utkal University, Bhubaneswar"
.sp .5
T}
\m[default]2009\m[linecolor];T{
.B "Bachelor of Science with Honours"
\(en University of Calcutta
.br
.I "erstwhile Presidency College, now Presidency University, Kolkata"
.sp .5
T}
.TE
\m[default]
.heading "Awards & Achievements"
.TS
tab(;) nospaces;
rW10|lx.
\m[default]2014\m[linecolor];T{
.B "Joint CSIR-UGC National Eligibility Test (NET) for JRF & LS"
\(en CSIR
.br
Rank
\(en
.I "CSIR 064"
.sp .5
T}
\m[default]2013\m[linecolor];T{
.B "Joint CSIR-UGC National Eligibility Test (NET) for JRF & LS"
\(en CSIR
.br
Rank
\(en
.I "UGC 048"
.sp .5
T}
\m[default]2012\m[linecolor];T{
.B "Graduate Records Examination (GRE)"
\(en ETS
.br
Percentile Rank
\(en
\(bu
.I "Verbal Reasoning"
\(en
.I 64
\(bu
.I "Quantitative Reasoning"
\(en
.I 82
.br
.B "Test of English as a Foreign Language (TOEFL)"
\(en ETS
.br
Scaled Score
\(en
.I 098
.sp .5
T}
\m[default]2011\m[linecolor];T{
.B "Graduate Aptitude Test in Engineering (GATE)"
\(en IIT Madras
.br
Rank
\(en
.I 515
.sp .5
T}
\m[default]2010\m[linecolor];T{
.B "Joint CSIR-UGC National Eligibility Test (NET) for JRF & LS"
\(en CSIR
.br
Rank
\(en
.I "CSIR 091"
.sp .5
T}
\m[default]2006\m[linecolor];T{
.B "DST-Kishore Vaigyanik Protsahan Yojana (KVPY) Fellowship"
\(en IISc Bangalore
.br
.B "National Level Science Talent Search Examination (NSTSE)"
\(en Unified Council India, Hyderabad
.br
Rank
\(en
.I 352
.sp .5
T}
.TE
\m[default]
.heading "Publications & Posters"
.TS
tab(;) nospaces;
rW10|lx.
\m[default]2020\m[linecolor];T{
Sarkar, A., Sharma, S., Agnihotri, P.,
.B "Sarkar, T.",
Kumari, P., Malhotra, R., Datta, B., Kumar, K., Biswas, S.
.I "Synovial fluid cell proteomic analysis identifies upregulation of \[*a]-taxilin proteins in rheumatoid arthritis: a potential prognostic marker."
Journal of Immunology.
DOI: 
.B "10.1155/2020/4897983"
T}
\m[default]2014\m[linecolor];T{
.B "38th All India Cell Biology Conference and International Symposium"
on
.I "Cellular Response to Drugs"
\(en CSIR-Central Drug Research Institute (CDRI).
T}
.TE
\m[default]
.heading "References"
.TS
tab(;) nospaces;
rW15|lx.
\m[default]Dr. Sagarika Biswas\m[linecolor];T{
Scientist 'F', CSIR-IGIB, Proteomics lab, Room 311, North Campus, Mall Road, near Jubilee Hall, Delhi University campus, Delhi
\(en 110007.
Email: 
.I "sagarika.biswas@igib.res.in"
Phone: +91-1127662581
.sp .5
T}
\m[default]Dr. Dakshayani Mahapatra\m[linecolor];T{
Assistant Professor (WBES), Dept. of Physiology, Government General Degree College, Mohanpur, Paschim Medinipur, WB. PIN
\(en 721436.
Email:
.I "dakshayani.mahapatra@gmail.com"
Phone: +91-9830655682
.sp .5
T}
\m[default]Dr. Sumit Kumar Gautam\m[linecolor];T{
Lead Scientist, Clear Meat Pvt. Ltd., B 78, First Floor, Sector 2, Noida, Near Sector 15 Metro Station. PIN
\(en 201301.
Email:
.I "sumit.k@clearmeat.com"
Phone: +91-8826954099
T}
.TE
