.nr PS 12p
.nr VS 10p
.nr PSINCR 6p
.nr GROWPS 1.5
.FAM T
.nr HM 0.75i
.nr FM 0.75i
.nr PO 0.75i
.nr LL 7i

.TL
Tanmoy Sarkar
.AU
seniorsarkar.de\[at]gmail.com
.AU
+91-7982143662

.NH 1
Resume Objective
.PP
A motivated research scholar with experience in biological studies and statistics, with a keen interest in computers. I like to look for the greater scheme of things in the minutest of details.

.NH 1
Experience
.NH 2
Worked as a PhD research scholar at CSIR-Institute of Genomics & Integrative Biology (IGIB), New Delhi from August 2014 to December 2021.
.SH
Adviser
.QS
Dr. Sagarika Biswas
.QE
.SH
Dissertation
.QS
Cytokine-mediated modulation of stem cell behavior in rheumatoid arthritis.
.QE
.SH
Accomplishments:
.IP 1.
Establishment of a viable cell culture laboratory setup.
.IP 2.
Dissection of 
.I "Rattus norvegicus"
and extraction of live stem cells by femoral flushing.
.IP 3.
Establishment of viable primary cell culture and cytokine treatments.
.IP 4.
Proteomic and statistical analyses.

.NH 2
Worked as a research assistant at Presidency University, Kolkata from December 2012 to July 2013.
.SH
Adviser
.QS
Dr. Prabir Mukherjee
.QE
.SH
Accomplishments:
.IP 1.
Arsenic toxicity studies on
.I "Rattus norvegicus"
.IP 2.
Histological assessments of 
.I "Rattus norvegicus"
tissue samples.

.NH 2
Worked as a PhD research scholar at Department of Biotechnology (DBT)-Centre for DNA Fingerprinting & Diagnostics (CDFD), Hyderabad from August 2011 to June 2012.
.SH
Adviser
.QS
Dr. Subhadeep Chatterjee
.QE
.SH
Dissertation
.QS
Plant-microbe interactions in Xanthomonas quorum sensing.
.QE
.SH
Accomplishments:
.IP 1.
Plasmid-mediated bacterial genetic engineering.
.IP 2.
Establishment of plant-bacterial co-cultures.

.NH 2
Completed Masters dissertation at Utkal University, Bhubaneswar from January 2011 to July 2011.
.SH
Adviser
.QS
Dr. Priyankar Sen
.QE
.SH
Dissertation
.QS
Age-dependent DNA methylation at catalase gene promoter region of 
.I "Rattus norvegicus".
.QE
.SH
Accomplishments:
.IP 1.
Methylation-sensitive restriction enzyme-mediated digestion of genomic DNA.
.IP 2.
Polymerase chain reaction (PCR)-mediated DNA fragment amplification.
.IP 3.
Sodium bisulfite conversion of amplified fragments and analysis.

.NH 2
Completed Bachelors dissertation at Presidency College, Kolkata at January 2009.
.SH
Adviser
.QS
Late Dr. Chandan Mitra
.QE
.SH
Dissertation
.QS
Assessment of physiological, ergonomical and hematological parameters of tribal populations in Madhya Pradesh, India.
.QE
.SH
Accomplishments:
.IP 1.
Respiratory survey using pneumography.
.IP 2.
Anthropometric profiling.
.IP 3.
On-field hematological testing and surveying.

.2C
.NH 1
Skills
.NH 2
Medical Physiology
.NH 3
Experimental Physiology

.IP \(bu
Kymography
.TS
box	tab(@);
c c
l lx.
Muscles@Parameters
_@_
Cardiac@Load
T{
Skeletal Gastrocnemius
T}@Temperature
T{
Smooth Intestinal
T}@Perfusion
-@T{
Fluid pressure
T}
-@T{
Ion concentrations
T}
-@Hypoxia
-@T{
Acetylcholine and Adrenaline
T}
.TE
.IP \(bu
Ringer's solution preparation

.NH 3
Work Physiology
.IP \(bu
Sphygmomanometric measurement of arterial blood pressure
.IP \(bu
Modified Harvard Step Test for physical fitness
.IP \(bu
Pneumographic recordings of respiratory movements
.IP \(bu
Spirometric measurement of vital capacity

.NH 3
Histology
.IP \(bu
Silver Nitrate staining
.IP \(bu
Hematoxylin-Eosin staining
.IP \(bu
Identification of permanent slides
.IP \(bu
Preparation of permanent slides
.RS
.IP a.
Fixing
.IP b.
Dehydrating
.IP c.
Paraffin embedding
.IP d.
Preparing blocks for microtomy
.IP e.
Microtomy and staining
.RE

.NH 3
Hematology
.IP \(bu
Leishman's staining of blood film
.IP \(bu
Blood corpuscular identification - basophils, eosinophils, neutrophils, monocytes, megakaryocytes
.IP \(bu
Using hemocytometer for counting
.RS
.IP a.
Total count of red blood corpuscles (RBCs)
.IP b.
Total count of white blood corpuscles (WBCs)
.IP c.
Differential count of WBCs
.RE

.NH 3
Biochemistry
.XP
Calculation of
.IP \(bu
Blood sugar by Folin-Wu method
.IP \(bu
Serum protein by Biuret method
.IP \(bu
Blood uric acid by cyanide-free method
.IP \(bu
Serum urea by DAM method
.IP \(bu
Percentage of lactose in milk by Benedict's method

.NH 3
Ergonomics
.LP
Measurement of anthropometric parameters for calculations like Body Mass Index (BMI), ponderal index:
.IP \(bu
Stature
.IP \(bu
Weight
.IP \(bu
Eye height
.IP \(bu
Shoulder height
.IP \(bu
Eye height (sitting)
.IP \(bu
Elbow height
.IP \(bu
Sitting height
.IP \(bu
Elbow rest height (sitting)
.IP \(bu
Knee height (sitting)
.IP \(bu
Shoulder elbow length
.IP \(bu
Arm reach from wall
.IP \(bu
Elbow-to-elbow breadth
.IP \(bu
Knee-to-knee breadth (sitting)
.IP \(bu
Shoulder breadth
.IP \(bu
Head length
.IP \(bu
Head breadth
.IP \(bu
Head circumference
.IP \(bu
Neck circumference
.IP \(bu
Mid-arm circumference
.IP \(bu
Waist circumference
.IP \(bu
Hip circumference
.IP \(bu
Chest circumference.

.NH 3
Microbiology
.IP \(bu
Gram staining of bacteria
.IP \(bu
Suspension culture of
.I "Escherichia coli"
(E. coli)
.IP \(bu
Protein extraction and estimation from E. coli
.IP \(bu
Plasmid extraction and estimation from E. coli

.NH 3
Animal handling
.LP
Ethics committee and animal facility approved dissection of animals and collection of samples for further experiments.

.NH 2
Stem Cell Culture
.NH 3
Primary cell culture
.IP \(bu
Isolation of tissue
.IP \(bu
Tissue disaggregation by
.RS
.IP a.
Cold trypsinization
.IP b.
Mechanical disaggregation
.RE
.IP \(bu
Enrichment of viable cells by Ficoll-Hypaque method

.NH 3
Cryopreservation in liquid Nitrogen
.IP \(bu
Ampoule preparation
.IP \(bu
Cytotoxicity studies by
.RS
.IP a.
Trypan Blue staining
.IP b.
MTT assay
.RE

.NH 3
Cell separation
.IP \(bu
Density gradient centrifugation
.IP \(bu
Fluorescence-Assisted Cell Sorting (FACS)

.NH 3
Cell characterization
.IP \(bu
Microscopy
.RS
.IP a.
Inverted microscopy
.IP b.
Compound microscopy
.IP c.
Confocal microscopy
.RE
.IP \(bu
Cell staining
.RS
.IP a.
Giemsa staining
.IP b.
Crystal Violet staining
.RE
.IP \(bu
Immunostaining using monoclonal antibodies and polyclonal antisera
.RS
.IP a.
Enzyme-linked Immunosorbent Assay (ELISA)
.IP b.
Peroxidase-anti-peroxidase (PAP) staining
.RE

.NH 3
Cell quantitation
.IP \(bu
Cell counting using hemocytometer
.IP \(bu
Cell proliferation measurement using population doubling time
.IP \(bu
Plating efficiency calculation

.NH 3
Culture maintenance
.IP \(bu
Subculture and propagation following split ratios at subculture intervals
.IP \(bu
Complete media formulation and replacement
.IP \(bu
Serum handling and heat inactivation
.IP \(bu
Administration of antibiotics
.IP \(bu
Laminar air-flow (LAF) hood maintenance and checking for contamination

.NH 3
Cell lysis for further studies
.IP \(bu
Preparation of cellular extracts by homogenization
.IP \(bu
Formulation of lysis buffers
.IP \(bu
Differential fractionation using Tween20
.IP \(bu
Protein estimation using Bradford assay

.NH 2
Molecular Biology
.NH 3
Proteomics
.IP \(bu
Sodium dodecylsulphate (SDS) polyacrylamide gel electrophoresis (PAGE)
.IP \(bu
2-dimensional PAGE (2D-PAGE)
.IP \(bu
Isoelectric focusing (IEF) using immobilized pH gradients (IPG) gel strips
.IP \(bu
Coomassie Brilliant Blue (CBB) and Ponceau gel staining
.IP \(bu
Mass spectrometer (MS)-compatible silver nitrate staining
.IP \(bu
Western blotting
.IP \(bu
Enzyme-linked Immunosorbent Assay (ELISA)
.IP \(bu
Matrix-assisted laser desorption-ionization (MALDI) time-of-flight (TOF) MS analysis

.NH 3
Gene Cloning and Vector Engineering
.IP \(bu
pBR322 plasmid
.IP \(bu
Primer designing 
.RS
.IP a.
BLAST
.IP b.
FASTA3
.IP c.
ClustalW
.RE
.IP \(bu
Restriction mapping using restriction endonucleases

.NH 3
Epigenetic profiling
.IP \(bu
Sodium bisulfite treatment of promoter region CpG islands

.NH 3
DNA/RNA Extraction, Quantification and Amplification
.IP \(bu
Agarose gel electrophoresis
.IP \(bu
Ethidium bromide (EtBr) staining
.IP \(bu
Southern blotting
.IP \(bu
Polymerase Chain Reaction (PCR)
.RS
.IP a.
Reverse Transciptase PCR (RT-PCR)
.IP b.
Quantitative Real Time PCR (qRT-PCR)
.RE

.NH 3
Bacterial Cell Culture
.IP \(bu
Media preparation for suspension broth and agar-based gel culture
.IP \(bu
Transformation using electroporation

.NH 2
Statistics
.NH 3
Hypothesis testing using R
.IP \(bu
One-sample t-tests
.IP \(bu
Two-sample t-tests
.IP \(bu
One-sample z-tests
.IP \(bu
Two-sample z-tests
.IP \(bu
Paired t-tests
.IP \(bu
Mann-Whitney tests
.IP \(bu
Chi-square tests

.NH 3
Regression modeling using R
.IP \(bu
One-way analysis of variance (ANOVA)
.IP \(bu
Two-way ANOVA

.NH 3
Using R for calculating
.IP \(bu
standard deviation
.IP \(bu
standard error
.IP \(bu
error bars
.IP \(bu
correlation coefficient

.NH 3
Other necessary statistical skills not requiring R include
.IP \(bu
statistical modeling
.RS
.IP a.
regression model
.IP b.
categorical regression model
.IP c.
multivariate regression model or ANOVA model
.RE
.IP \(bu
sample size determination
.RS
.IP a.
effect size
.IP b.
significance level
.IP c.
population variation
.RE

.1C
.NH 2
Computer Skills
.NH 3
GNU/Linux commandline interface (CLI) tools especially useful for academic research, of which I am well versed in:
.LP
.TS H
box	tab(@);
c c
l lx.
Name@T{
Academic Uses
T}
_@_
groff@T{
a simple document formatting system used for creating PDF documents including publications, resumes, articles, based on the original Unix troff/nroff \**
T}
tbl@T{
a table preprocessor program for groff
T}
refer@T{
a reference preprocessor program for groff
T}
LaTeX@T{
a more powerful typesetting system for creating PDFs
T}
BibTeX@T{
a reference management program for LaTeX
T}
imagemagick@T{
image manipulation useful for converting raw image files to .TIFF for publication, .JPEG for other purposes
T}
neovim@T{
a modern powerful text editor, based on the original vi editor
T}
grep@T{
search strings within documents
T}
find@T{
search for documents within the filesystem
T}
sed@T{
an in-line text editor
T}
xargs@T{
useful for piping commands in conjunction with other arguments
T}
awk@T{
a powerful pattern scanning and processing language
T}
fzf@T{
the commandline fuzzyfinder, important when you don't know the exact filename
T}
markdown@T{
quick and dirty notetaking language
T}
bash@T{
the Bourne-again Shell where all the magic happens
T}
diff@T{
useful for finding differences between two versions of a document, useful for collaboration, authoring academic papers, can be outputted to diff files
T}
patch@T{
apply diff files for changes to original file
T}
git@T{
version control system, useful for collaboration, rolling back changes, multi-author edits
T}
.TH
.TE

.FS
This document is prepared in neovim using groff.
.FE

.NH 3
GNU/Linux GUI tools necessary for image creation and quantification, useful for academic research of which I am familiar with:
.LP
.TS
box	tab(@);
c c
l lx.
Name@T{
Academic Uses
T}
_@_
ImageJ@T{
quantify image pixels used for semi-quantitative assessments
T}
Inkscape@T{
create raster-free vector images useful to illustrate models for publications
T}
OpenSCAD@T{
create vector 3D images for illustration of DNA and other biomolecules
T}
.TE

.NH 3
Other GNU/Linux tools:

.LP
.TS
box tab(@);
l l.
Sysadmin@Languages
_@_
systemd@C
ssh@Python
T{
mkfs
.br
top
T}
.TE

.1C
.NH 3
Instrumentation softwares, whose alternatives are not available in the Free and Open Source Software (FOSS) world of GNU/Linux, I am familiar with:
.LP
.TS
box	tab(@);
c c
l lx.
Name@Applications
_@_
T{
BD FACScalibur
T}@T{
for Fluorescence Assisted Cell Sorting
T}
T{
Roche LightCycler 480
T}@T{
for Real Time Polymerase Chain Reaction
T}
T{
Biorad Image Lab
T}@T{
for ChemiDoc MP gel documentation system
T}
T{
Nanodrop 1000
T}@T{
for DNA/RNA quantification
T}
PDQuest@T{
for analyzing 2D-PAGE gels
T}
.TE

.NH 1
Education

.LP
.TS
allbox	tab(@);
c c c c c
lx r r l lx.
Qualification@Year@T{
% Marks
T}@Division@University
T{
Master's of Science in Biotechnology
T}@2011@T{
79.4
T}@T{
First\**
T}@T{
Utkal University, Bhubaneswar
T}
T{
Bachelor's of Science (3-year course with Honours) in Physiology
T}@2009@T{
58.9
T}@T{
Second\**
T}@T{
University of Calcutta
T}
T{
All India Senior School Certificate Examination
T}@2006@T{
82.8
T}@T{
First\**
T}@T{
Central Board of Secondary Education
T}
T{
All India Secondary School Examination
T}@2004@T{
78.4
T}@T{
First\**
T}@T{
Central Board of Secondary Education
T}
.TE

.FS
Subjects: Cell Biology & Genetics, Biomolecules & Biophysical Chemistry, Microbial Physiology & Genetics, Biotechniques, Molecular Biology, Enzyme Technology, Immunology, Biostatistics, Animal Cell Culture, Genetic Engineering, Plant Biotechnology, Intermediary Metabolism, Environmental & Marine Biotechnology, Bioprocess Engineering & Technology
.FE
.FS
Subjects: Physiology Hons., Physics General, Chemistry General, Environmental Sciences, English Mandatory
.FE
.FS
Subjects: English, Mathematics, Physics, Chemistry, Biology, Information Practices
.FE
.FS
Subjects: English, Mathematics, Science, Social Sciences, Hindi
.FE

.NH 1
Honors and Awards
.LP
.TS H
box	tab(@);
c c c c c
lx l r r lx.
T{
Fellowship/Award
T}@Year@Rank@Score@T{
Bestowing Organization
T}
_@_@_@_@_
T{
Senior Research Fellowship (SRF)
T}@T{
August 2016
T}@NA@NA@T{
University Grants Commission (UGC)
T}
T{
National Eligibility Test for Lectureship (NET)-JRF
T}@T{
July 2015
T}@064@NA@T{
Council of Scientific & Industrial Research (CSIR)
T}
T{
Junior Research Fellowship (JRF)
T}@T{
August 2014
T}@NA@NA@T{
University Grants Commission (UGC)
T}
T{
National Eligibility Test for Lectureship (NET)-JRF
T}@T{
July 2014
T}@048@NA@T{
University Grants Commission (UGC)
T}
T{
National Eligibility Test for Lectureship (NET)-JRF
T}@T{
July 2011
T}@091@NA@T{
Council of Scientific & Industrial Research (CSIR)
T}
T{
Graduate Record Examinations (GRE) General Tests
T}@T{
May 2012
T}@NA@T{
052 \**
T}@T{
Educational Testing Service (ETS)
T}
T{
Graduate Aptitude Test in Engineering (GATE)
T}@2011@515@048@T{
Indian Institute of Technology Madras (IITM)
T}
T{
Kishore Vaigyanik Protsahan Yojana (KVPY) National Fellowships for Students Interested in Research Careers
T}@2006@NA@NA@T{
Indian Institute of Science (IISc), Bangalore
T}
T{
National Level Science Talent Search Examination (NSTSE)
T}@2006@352@060@T{
Unified Council India
T}
.TH
.TE
.FS
Average of:
.RS
.IP \(bu
Verbal Reasoning 064
.IP \(bu
Quantitative Reasoning 082
.IP \(bu
Analytical Writing 011
.RE
.FE

.NH 1
Publications
.NH 2
Research Article(s)
.IP \(bu
Sarkar, A., Sharma, S., Agnihotri, P.,
.B "Sarkar, T.",
Kumari, P., Malhotra, R., Datta, B., Kumar, V., Biswas, S.\** Synovial fluid cell proteomic analysis identifies upregulation of alpha-taxilin proteins in rheumatoid arthritis: a potential prognostic marker.
.I "Journal of Immunology".
2020. DOI: 10.1155/2020/4897983

.FS
Corresponding author: Sagarika Biswas sagarika.biswas@igib.res.in
.FE

.NH 2
Conferences

.NH 3
Attended/Organized
.LP
.TS
box	tab(@);
c c c
lx r lx.
Name@Year@Organization
_@_@_
T{
Emerging Trends in Biotechnology & Drug Discovery
T}@2017@T{
CSIR-Institute of Genomics & Integrative Biology (IGIB), New Delhi
T}
T{
18th Annual Conference of the Physiological Society of India
T}@2006@T{
Department of Physiology, Presidency College, Kolkata
T}
.TE

.NH 3
Poster presented
.LP
.TS
box	tab(@);
c c c
lx r lx.
Name@Year@Organization
_@_@_
T{
38th All India Cell Biology Conference and International Symposium on
.I "Cellular Response to Drugs"
T}@2014@T{
CSIR-Central Drug Research Institute(CDRI), Lucknow
T}
.TE

.NH 1
Other Activities

.LP
.TS
tab(@) nospaces;
l l.
Indoor@Outdoor
_@_
T{
Reading novels
T}@Traveling
T{
Looking at maps
T}@Hiking
T{
Pondering local histories
.br
Looking up train schedules and routes
.br
Cooking
.br
Listening to podcasts
.br
Table tennis
T}@Camping
.TE

.NH 1
Personal Details
.LP
.TS
box	tab(@);
c c
l l.
Particulars@Details
_@_
T{
Date of Birth
T}@T{
24th September 1988
T}
T{
Father's Name
T}@T{
Tapan Kumar Sarkar
T}
T{
Mother's Name
T}@T{
Sabitri Sarkar
T}
Gender@Male
T{
Marital Status
T}@Married
T{
Spouse's Name
T}@T{
Supriya Sarkar Ghosh
T}
Locality@T{
Kampa Lake Road
T}
Landmark@T{
Near Kampa Pumphouse
T}
Vill@Nagdaha
T{
P.O.
T}@Kampa
City@Kanchrapara
T{
R.S.
T}@Kanchrapara
T{
P.S.
T}@Bizpur
T{
Dist.
T}@T{
North 24 Parganas
T}
State@T{
West Bengal
T}
Nation@INDIA
PIN@743193
.TE

.NH 1
Languages
.IP \(bu
.B Bengali
Native proficiency
.IP \(bu
.B English
Professional working efficiency \**

.FS
Test of English as Foreign Language (TOEFL) Internet-based Test (iBT) score of 098/120, August 2012
.FE

.NH 1
References
.IP 1.
.B "Dr. Sagarika Biswas",
Scientist 'F', CSIR-IGIB, Proteomics lab, Room 311, North Campus, Mall Road, near Jubilee Hall, Delhi University campus, Delhi. PIN 110007. Phone: +91-1127662581
.IP 2.
.B "Dr. Dakshayani Mahapatra",
Assistant Professor (W.B.E.S), Department of Physiology, Government General Degree College, Mohanpur, Paschim Medinipur, West Bengal. PIN 721436. Email: dakshayani.mahapatra@gmail.com. Phone: +91-9830655682
.IP 3.
.B "Dr. Sumit Kumar Gautam",
Lead Scientist, Clear Meat Pvt. Ltd., B 78, First Floor, Sector 2, Noida, Near Sector 15 Metro Station. PIN 201301. Email: sumit.k@clearmeat.com. Phone: +91-8826954099
